### ISSUE TITLE
Display of images in questions and options

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1636]
### Analysis:
Among the three options here, to identify which one is better, below are the information gathered:

<img width="657" alt="Image" src="https://github.com/user-attachments/assets/34ee6ede-0445-457e-8a12-f8f4821fe0aa" />

### JSS:
- Currently some VHWs also use Shwaas
- In Shwaas now without clicking image they are able to collect
- They will be using it to collect data everyday - so more probability to memorise it
- The workers have basic health related knowledge
- Initially they told scrolling is better than clicking everything, after the above questions they were also not sure.

### IPH:
- The users are nurses who have degrees
- But they will use the app to collect only once/twice in a week. So visualisations will help them to recollect what was shown in ppt during training.
- Once they become well-trained, then they don't rely on flip charts.
- They prefer thumbnails though in survey it was mentioned otherwise so that without scrolling much the thumbnails can be used to remind the nurses 

### Decision made:
 Showing thumbnails seem to be sufficient. But we can retain the Avni theme of text for options and selection for consistency and better understandability. This will help in satisfying both user personas -> neo-literates and literates by just changing the image icon size.
<img width="294" alt="Image" src="https://github.com/user-attachments/assets/d8faa728-f869-4679-bdf2-afbd64f20b82" />

### AC:
- Fetch the images during sync.
- Sync should fail if the above fails.
- Show small icon image to the right of question when question has image. Similarly to the right of options.
- When we show the small icon image retain the aspect ratio of bigger image. 
- On click of image it should show the bigger actual image. On click of the opened image at any place, it should close.
- Should work with both single and multi-select. 
- - If only one of the option has image as well, show the options in one column format instead of 2 column format.
- When following any of the above doesn't look good,  try out some UX options and discuss whatever works with the analyst/team.
- Support within QG and RQG
- Clicking on radio button or checkbox or the text should mean selection like now. 

<img width="294" alt="Image" src="https://github.com/user-attachments/assets/d8faa728-f869-4679-bdf2-afbd64f20b82" />

### Technical discussion:
- Save as html 
- Media type and media columns
- Gap between 2 questions
- page size of concepts smaller? or download from s3?
- spike card.
- options with images - always one column format

**Comment by himeshr** [comment]
## Sample screenshots

<img width="1728" alt="Comparisons" src="https://github.com/user-attachments/assets/56c54092-c134-4c89-aa4e-e0abc7ef4dea" />
<img width="292" alt="Image" src="https://github.com/user-attachments/assets/626b2707-b75d-4d59-b1e4-336b1e5fa410" />
<img width="292" alt="ImageBlownUp" src="https://github.com/user-attachments/assets/c663b32b-c619-41c8-93c1-c0456622e75c" />
<img width="292" alt="SingleSelectMandatoryReadOnly" src="https://github.com/user-attachments/assets/643ee1ed-b596-4c2e-b5ca-dc80954f1570" />
<img width="292" alt="MultiSelectErrorOnNoSelection" src="https://github.com/user-attachments/assets/207e4c99-ded2-464a-81cb-cb7a68ba3510" />
<img width="261" alt="MissingMediaSyncError" src="https://github.com/user-attachments/assets/fd901bfc-ee45-49ec-91f2-d75197fc2b27" />
<img width="270" alt="MissingMediaStillAllowsFormFilling" src="https://github.com/user-attachments/assets/abaa5d6f-0695-48e7-ae9a-5a78d0821ffb" />

**Comment by himeshr** [comment]
### test cases

https://gist.github.com/himeshr/ae57ceb3f4baa08e1aad478c34fe86a0

**Comment by himeshr** [comment]
@mahalakshme ~Will not fail sync on missing media, as we might break sync across lot of old organisations, where data is missing in s3 for whatever reason.~

#### ~Not gonna do below~ We are goona do this, only for concept metadata icons download

<img width="261" alt="MissingMediaSyncError" src="https://github.com/user-attachments/assets/fd901bfc-ee45-49ec-91f2-d75197fc2b27" />

**Comment by mahalakshme** [comment]
@himeshr We need not handle data missing in s3. But say sync of media fails for some other reason like timeout etc, then we should show error

**Comment by himeshr** [comment]
Pending:
--------
- [x] translations
- [x] devbox

**Comment by himeshr** [comment]
### Question Group
<img width="330" alt="Question Group" src="https://github.com/user-attachments/assets/a0715099-69d4-42eb-912d-978be3d6f0b8" />

### Repeatable Question Group
<img width="330" alt="Repeatable Question Group" src="https://github.com/user-attachments/assets/58c9b3f5-f729-4c32-adbd-00402849be7e" />

**Comment by 1t5j0y** [comment]
we will need to take care of (now or during merge):
1. models schema version was changed to 200 in 13.0 so the schema version for this change will need to be bumped

**Comment by dinesh2096** [comment]
- [ ] When we added the image the web app is getting crashed 
- [ ] Suggestion can we give the review image or small view of image(Thumbnail) because user unable to identify the image is uploaded or not 

Reference video : 

https://drive.google.com/file/d/1jM9yaNVpCzwh6RlQvyJfbpbtL7qmPqmc/view?usp=drive_link

**Comment by petmongrels** [comment]
1. caused by merge issue
2. concept image will not be available on the form designer page
3. removed concept image support from non-coded and NA concepts

**Comment by petmongrels** [comment]
the bug is for the other card. whose commit is - https://github.com/avniproject/avni-webapp/commit/52db72ed90e69f95403c9219a7b8a227a2261755

**Comment by dinesh2096** [comment]
- [ ] Now we are missing the icon option in the code concept deployed latest 13.1 

https://drive.google.com/file/d/1oXgOkiBmORtmQobhWp9UVIovtv-37TKD/view?usp=drive_link

**Comment by petmongrels** [comment]
>> concept image will not be available on the form designer page
- the point 2 above

**Comment by dinesh2096** [comment]
- [ ] Webapp is getting crashed 

Reference video : 

https://drive.google.com/file/d/1cuqkZCMx9vTiWXlFe8-LHmQnKWzJJOEG/view?usp=drive_link

**Comment by petmongrels** [comment]
fixed

**Comment by dinesh2096** [comment]
Forgot to mention 
Env : pre-release 
org : dineshbootcamp
user : acha@dineshbootcamp

- [x] Need to check below image why it is showing error even though it is come under the requirement (Image link : https://drive.google.com/file/d/1t117Re83L-7atuWFYu0LptzIPKJdnOBN/view?usp=drive_link)
- [ ] The error is displayed if we upload the wrong image format and if we uploaded the fixed image then the error is still displayed confuse the user. 
- [x] If we want to remove or any other option we unable to delete it or move the options
Reference video : 
https://drive.google.com/file/d/1uyHWMr2YxJPxJgaB6_9djmXV2ofJJRQO/view?usp=drive_link
- [ ] We need to resize the image view like gif that will be nice to look
- [x] Gif is shown as image in the cilent app 
- [x] Suggesstion if we click on the image in the cilent app it is pop up but if the user again click on it can we maxmize the image so the user can see it as their requirement
- [ ] Standard the image view in the webapp some image shows bigger some shows smaller 
- [x] And also image pixel is breaking refer the below image

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/aae8f38d-cbce-472b-be66-6833948f2a3d" />

**Comment by petmongrels** [comment]
- I have fixed the issues related to web app
- don't have context of ACs related to mobile app @himeshr

**Comment by himeshr** [comment]
Will look into them now..

**Comment by himeshr** [comment]
## Client side issues reported are as follows:
 - [ ] Gif is shown as image in the cilent app => this is working as designed, we do not support GIFs display on Client. And since the GIF is displayed as image, which is legible, should be fine for end user perspective.

 - [ ] Suggesstion : If we click on the image in the cilent app it is pop up but if the user again click on it can we maxmize the image so the user can see it as their requirement => Tried out the change, it looked irregular for different iamge dimesnions, would prefer to retain existing behaviour as is

 - [x] And also image pixel is breaking refer the below image => this happens when there is misfit between image dimensions and the modal display allowed size.. Have fixed it as follows.

<img width="592" alt="Image" src="https://github.com/user-attachments/assets/30f6a733-ff71-4c59-a8f0-de6712d7c43a" />

**Comment by dinesh2096** [comment]
- [ ] Issue is exists -  The error is displayed if we upload the wrong image format and if we uploaded the fixed image then the error is still displayed confuse the user.

https://drive.google.com/file/d/1EYxGY48DOmstlOW-vmtQS1RaZ5NzrRdr/view?usp=drive_link

- [ ] We need to resize the image view in standard way 

https://drive.google.com/file/d/16aXGusww54IwvMYrSnUFSleNtSppyJcd/view?usp=drive_link

**Comment by dinesh2096** [comment]
Test case: 

- [x] Tested the image is getting accepted as per the requirment 
- [x] Tested the error is displayed if the image type and kb is greater than given requirment
- [x] Tested by adding the image in the concept 
- [x] Tested by removing the image in the concept 
- [x] Tested by removing and added the other image in the concept
- [x] Tested by updating the image in the concept
- [x] Tested by removing the entire concept and validate in the cilent app 
- [x] Tested by opening the image is it breaking both webapp and cilent app 
- [x] Tested by adding the concept in question groups
- [x] Tested by adding the concept in repetable question group 
- [x] Tested by adding the rules in the concept and also in the previous concept
- [x] Teste by accessing the image from the form level and also in concept level.
- [x] Tested the ETL is getting synced without any issues.
